// ===== LAYER 3: IMPACT RULES =====
// Scenario-to-indicator adjacency list. Each rule defines how a scenario affects a target indicator.
// Static, versioned, authoritative — the deterministic source of truth.
//
// sign:       'up' | 'down' | 'mixed'
// strength:   1–5 integer scale
// lag:        'immediate' | 'short' | 'medium' | 'long'
// confidence: 1–5 integer scale
// mechanism:  references MECHANISMS[].id (from mechanisms.js)

const IMPACT_RULES = [

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_hike_hawkish_surprise
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hike-to-fed-funds',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'fed-funds-target',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed directly sets the fed funds rate — a hike raises it mechanically.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.4 },
    },
    {
        id: 'hike-to-2y',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'A hawkish surprise reprices the expected fed funds path upward, lifting 2Y yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hike-to-10y',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Hawkish surprise pushes 10Y up via term premium, but growing recession fears push it down (curve flattening).',
        conditionalOn: null, exceptions: ['At zero lower bound, effect is muted'],
        regimeOverrides: {
            late_cycle: { sign: 'mixed', strength: 2, confidence: 3 },
            recession_risk: { sign: 'down', strength: 2, confidence: 3 },
            financial_stress: { sign: 'down', strength: 2, confidence: 2 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hike-to-mortgage',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Higher yields pass through to mortgage rates with a short lag.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-sp500',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Higher rates raise discount rates, pressuring equity valuations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            inflation_scare: { strength: 2 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-nasdaq',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth/tech stocks are especially rate-sensitive due to long-duration cash flows.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5 },
            inflation_scare: { strength: 3 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-dow',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Dow falls but less than Nasdaq — its value-heavy composition is less rate-sensitive.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-vix',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Hawkish surprises increase uncertainty, lifting volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: { small: 0.5, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-corporate',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Higher benchmark yields widen credit spreads and raise corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-housing',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 3, lag: 'medium', confidence: 4,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher mortgage rates make housing less affordable, reducing new construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            recession_risk: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-spending',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter financial conditions reduce disposable income and credit access.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-gdp',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter conditions slow investment and consumption, dragging on GDP over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-core-cpi',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter conditions slow demand and reduce pricing power, easing core inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-core-ppi',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'core-ppi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Demand slowdown reduces producer-side price pressure with a long lag.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-headline-cpi',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'headline-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Broad price level eases as tighter financial conditions cool demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-headline-ppi',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'headline-ppi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Reduced demand pressure lowers wholesale prices over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-pce',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'pce',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'PCE inflation eases as tighter policy cools consumer demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-core-pce',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'core-pce',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'The Fed\'s preferred inflation gauge eases as tightening suppresses demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-unemployment',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter conditions slow growth and hiring, pushing unemployment higher over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-job-openings',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Firms pull back on job postings as financial conditions tighten and demand slows.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hike-to-wages',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Labor market slack from tighter policy reduces wage pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-oil',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Hawkish surprise strengthens USD and signals growth slowdown, reducing oil demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 3, sentiment: 'negative' },
            financial_stress: { strength: 3, sentiment: 'negative' },
        },
        surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_higher_for_longer
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hfl-to-forward-guidance',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'forward-guidance',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed explicitly signals rates will remain elevated for longer.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hfl-to-2y',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Markets push out the expected timeline for rate cuts, lifting short-end yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hfl-to-10y',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Higher-for-longer signals lift term premium, pushing 10Y yields up.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { sign: 'mixed', strength: 2, confidence: 2 },
            inflation_scare: { strength: 5, confidence: 5 },
            financial_stress: { sign: 'down', strength: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-sp500',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Extended high rates pressure equity valuations through higher discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            inflation_scare: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-nasdaq',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks suffer most from sustained high rates due to duration sensitivity.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 5 },
            recession_risk: { strength: 5 },
            inflation_scare: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-mortgage',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Sustained high yields keep mortgage rates elevated.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-housing',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 3, lag: 'medium', confidence: 4,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Persistently high mortgage rates dampen housing demand and construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-spending',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Sustained tight financial conditions erode disposable income and credit access.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 3, lag: 'short' },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 4, lag: 'short' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-gdp',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Persistently tight conditions drag on investment and consumption, slowing GDP.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1, confidence: 2 },
            late_cycle: { strength: 3, lag: 'medium' },
            recession_risk: { strength: 4, lag: 'medium' },
            financial_stress: { strength: 4, lag: 'medium' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-corporate',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Sustained high benchmark yields keep corporate borrowing costs elevated.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5, lag: 'immediate' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-unemployment',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Extended tight conditions slow hiring and gradually push unemployment higher.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 3, lag: 'medium' },
            recession_risk: { strength: 3, lag: 'medium' },
            financial_stress: { strength: 3, lag: 'medium' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-core-cpi',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Sustained restrictive policy cools demand and eases core inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 4, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-core-ppi',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'core-ppi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Extended demand slowdown reduces producer-side price pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 3, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-headline-cpi',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'headline-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Persistent restrictive stance gradually weighs on the broad price level.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 3, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-headline-ppi',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'headline-ppi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Sustained demand pressure reduction lowers wholesale prices over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 3, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-pce',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'pce',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'PCE inflation eases as sustained tight policy cools consumer demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 3, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-core-pce',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'core-pce',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'The Fed\'s preferred inflation gauge eases under persistent restrictive conditions.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3, confidence: 4, lag: 'medium' },
            inflation_scare: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2, sentiment: 'neutral' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-oil',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Oil falling might be a mild positive, cheaper energy = consumer relief.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            inflation_scare: { sign: 'up', strength: 3, sentiment: 'negative' },
            recession_risk: { sentiment: 'negative' },
            financial_stress: { strength: 3, sentiment: 'negative' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-dow',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Sustained high rates weigh on Dow valuations, though less than growth stocks.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            inflation_scare: { strength: 3 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-vix',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Higher-for-longer signals increase policy uncertainty, lifting volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            inflation_scare: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-job-openings',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Sustained tight conditions cool hiring plans and reduce job postings.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 3, lag: 'short' },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3, lag: 'short' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-wages',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Extended restrictive policy builds labor market slack, easing wage pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 1 },
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_cut_dovish_surprise
    // ═══════════════════════════════════════════════════════════
    {
        id: 'cut-to-fed-funds',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'fed-funds-target',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed directly lowers the fed funds rate.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.4 },
    },
    {
        id: 'cut-to-2y',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'A dovish surprise reprices the fed funds path lower, pulling 2Y yields down.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'cut-to-10y',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Dovish surprise lowers 10Y yields, though growth optimism can partially offset.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 4 },
            inflation_scare: { sign: 'up', strength: 2, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-sp500',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'sp-500',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Lower rates reduce discount rates, boosting equity valuations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 4 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4, confidence: 4 },
            inflation_scare: { sign: 'down', strength: 2, confidence: 2 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-nasdaq',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'nasdaq',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks benefit most from lower rates due to duration sensitivity.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 5 },
            recession_risk: { strength: 2, confidence: 2 },
            inflation_scare: { sign: 'down', strength: 1, confidence: 2 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-mortgage',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'mortgage-rates',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Lower yields pass through to mortgage rates, improving affordability.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            inflation_scare: { sign: 'up', strength: 2, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-housing',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'housing-starts',
        sign: 'up', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Lower mortgage rates stimulate housing demand and new construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-vix',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'vix',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Dovish surprises reduce uncertainty, compressing volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 4, confidence: 4 },
            inflation_scare: { sign: 'up', strength: 2, confidence: 2 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-spending',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'consumer-spending',
        sign: 'up', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier financial conditions boost disposable income and credit access.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-gdp',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'gdp-growth',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier conditions stimulate investment and consumption, supporting GDP.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-corporate',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Lower benchmark yields reduce corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-dow',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'dow',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Lower rates support Dow valuations via reduced discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            inflation_scare: { sign: 'down', strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-unemployment',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'unemployment',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier conditions support hiring and gradually lower unemployment.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-core-cpi',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'core-cpi',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier conditions eventually support demand and push core inflation higher.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-core-ppi',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'core-ppi',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Demand recovery from easier conditions adds producer-side price pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-headline-cpi',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'headline-cpi',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier monetary conditions gradually push the broad price level higher.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-headline-ppi',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'headline-ppi',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Demand recovery from easier conditions lifts wholesale prices over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-pce',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'pce',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'PCE inflation rises as easier policy lifts consumer demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-core-pce',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'core-pce',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'The Fed\'s preferred inflation gauge drifts higher as easing supports demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-oil',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'up', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Dovish surprise weakens USD and signals growth support, lifting oil demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-wages',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'wage-growth',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier conditions tighten the labor market over time, lifting wage pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-job-openings',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'job-openings',
        sign: 'up', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easier financial conditions encourage firms to expand hiring and post openings.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: core_pce_hotter_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hot-pce-to-core-pce',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'core-pce',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'Core PCE prints higher than expected — this is the direct data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-2y',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Hotter inflation pushes markets to price in fewer rate cuts or more hikes.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            inflation_scare: { strength: 5, confidence: 5 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hot-pce-to-10y',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Hot inflation lifts 10Y via inflation expectations, but growth fears can offset.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 2, confidence: 4 },
            late_cycle:       { strength: 2, confidence: 2 },
            recession_risk:   { sign: 'down', strength: 2, confidence: 3 },
            inflation_scare:  { strength: 4, confidence: 4 },
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-sp500',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Hot inflation means tighter policy ahead, pressuring equities.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 5 },
            inflation_scare: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-nasdaq',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks are hit hardest by hawkish repricing after hot inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5 },
            recession_risk: { strength: 5 },
            inflation_scare: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-core-cpi',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'core-cpi',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Persistent inflation pressure tends to show up in both PCE and CPI measures.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            inflation_scare: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-mortgage',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Hot inflation pushes yields up, passing through to mortgage rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk:   { strength: 1, confidence: 2 },
            financial_stress: { strength: 3, confidence: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-housing',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher expected rates from hot inflation weigh on housing affordability.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle:       { strength: 3, confidence: 3 },
            recession_risk:   { strength: 4, lag: 'short', confidence: 3 },
            financial_stress: { strength: 4, lag: 'short', confidence: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-spending',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher expected rates from sticky inflation tighten conditions and reduce spending.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 1, confidence: 2 },
            late_cycle:       { strength: 3, lag: 'short', confidence: 3 },
            recession_risk:   { strength: 4, lag: 'short', confidence: 4 },
            inflation_scare:  { strength: 3, confidence: 3 },
            financial_stress: { strength: 4, lag: 'short', confidence: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-corporate',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Hot inflation raises rate expectations, pushing corporate borrowing costs higher.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 1, confidence: 3 },
            late_cycle:       { strength: 3, confidence: 3 },
            recession_risk:   { strength: 4, lag: 'immediate', confidence: 4 },
            inflation_scare:  { strength: 3, confidence: 3 },
            financial_stress: { strength: 5, lag: 'immediate', confidence: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-gdp',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Sticky inflation prolongs tight financial conditions, weighing on growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 1, confidence: 2 },
            late_cycle:       { strength: 3, lag: 'medium', confidence: 3 },
            recession_risk:   { strength: 4, lag: 'medium', confidence: 4 },
            inflation_scare:  { strength: 3, confidence: 3 },
            financial_stress: { strength: 4, lag: 'medium', confidence: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-unemployment',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 1, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Prolonged tight conditions from sticky inflation eventually raise unemployment.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 1, confidence: 1 },
            late_cycle:       { strength: 2, lag: 'medium', confidence: 2 },
            recession_risk:   { strength: 3, lag: 'medium', confidence: 3 },
            inflation_scare:  { strength: 2, confidence: 2 },
            financial_stress: { strength: 3, lag: 'medium', confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-job-openings',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 1, lag: 'medium', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter expected policy from hot inflation gradually reduces hiring plans.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-core-ppi',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'core-ppi',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Broad inflation pressure shows up in producer prices as well.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-headline-cpi',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'headline-cpi',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Persistent core inflation pulls headline CPI higher.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-headline-ppi',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'headline-ppi',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Core PCE heat signals broad inflation pressure across producer prices.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-pce',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'pce',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Hot core PCE directly lifts headline PCE.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-dow',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Hot inflation signals tighter policy, weighing on Dow valuations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            inflation_scare: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-vix',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Hot inflation raises policy uncertainty and lifts volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            inflation_scare: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-oil',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 1, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Hot inflation implies tighter policy ahead, which reduces growth and oil demand over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 1, confidence: 1, sentiment: 'neutral' },
            late_cycle:       { strength: 2, confidence: 2 },
            recession_risk:   { strength: 3, confidence: 3, sentiment: 'negative' },
            inflation_scare:  { sign: 'mixed', strength: 1, confidence: 1, sentiment: 'neutral' },
            financial_stress: { strength: 2, confidence: 2, sentiment: 'negative' },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-wages',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'wage-growth',
        sign: 'up', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Hot inflation raises wage demands as workers seek to keep up with prices.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing:     { strength: 3, confidence: 3 },
            late_cycle:       { strength: 1, confidence: 2 },
            recession_risk:   { sign: 'down', strength: 3, lag: 'short', confidence: 3 },
            inflation_scare:  { strength: 3, confidence: 3 },
            financial_stress: { sign: 'down', strength: 2, lag: 'short', confidence: 2 },
        },
        surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: core_pce_cooler_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'cool-pce-to-core-pce',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'core-pce',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'Core PCE prints lower than expected — this is the direct data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-2y',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Cooler inflation data brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            inflation_scare: { strength: 5 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'cool-pce-to-sp500',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'sp-500',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Disinflation supports equities via lower expected discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 4 },
            recession_risk: { sign: 'mixed', strength: 1, confidence: 2 },
            inflation_scare: { strength: 5 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-nasdaq',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'nasdaq',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks rally on dovish repricing after cool inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 5 },
            recession_risk: { strength: 2, confidence: 2 },
            inflation_scare: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-10y',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Cooler inflation lowers 10Y via reduced inflation expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-mortgage',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'mortgage-rates',
        sign: 'down', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Cooler inflation pulls yields down, easing mortgage rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-housing',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'housing-starts',
        sign: 'up', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Lower expected rates from cool inflation improve housing affordability.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-spending',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'consumer-spending',
        sign: 'up', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easing inflation expectations loosen conditions and support spending.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-corporate',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'down', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Cool inflation lowers rate expectations, easing corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-gdp',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'gdp-growth',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Cooling inflation may ease conditions, supporting growth over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-unemployment',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'unemployment',
        sign: 'down', strength: 1, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easing conditions from falling inflation support hiring over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-job-openings',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'job-openings',
        sign: 'up', strength: 1, lag: 'medium', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Easing rate expectations from cool inflation encourage hiring.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-core-cpi',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cooling PCE signals broad disinflation that appears in CPI too.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-core-ppi',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'core-ppi',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Broad disinflation eases producer-side price pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-headline-cpi',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'headline-cpi',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cooling core inflation pulls headline CPI lower.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-headline-ppi',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'headline-ppi',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cooling PCE signals narrowing price pressure across wholesale prices.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-pce',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'pce',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cool core PCE directly pulls headline PCE lower.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-dow',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'dow',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Cool inflation supports Dow via lower expected discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-vix',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'vix',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Cool inflation reduces policy uncertainty, compressing volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { sign: 'up', strength: 1, confidence: 2 },
            inflation_scare: { strength: 4 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-oil',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'up', strength: 1, lag: 'short', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cool inflation signals easier policy ahead, supporting growth and oil demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-wages',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Falling inflation reduces wage demands as cost-of-living pressure eases.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: payrolls_wages_hot
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hot-labor-to-wages',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'wage-growth',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong payrolls and wage data directly show labor market heat.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-unemployment',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'unemployment',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong hiring typically pushes unemployment lower.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-2y',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Hot labor data signals the Fed may need to keep rates higher, lifting 2Y yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            recession_risk: { sign: 'mixed', strength: 2, confidence: 2 },
            inflation_scare: { strength: 4 },
        },
        surpriseScaling: null,
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'core-cpi',
        sign: 'up', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong wage growth can feed into services inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            inflation_scare: { strength: 4, confidence: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-spending',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'consumer-spending',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'More jobs and higher wages boost consumer spending power.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 4, confidence: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-sp500',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'sp-500',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Strong labor data signals economic resilience, supporting equities modestly.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { strength: 3 },
            inflation_scare: { sign: 'down', strength: 2, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-nasdaq',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'nasdaq',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Strong labor data supports growth stocks via positive growth outlook.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-dow',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'dow',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Strong employment data supports Dow via economic resilience.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-vix',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'vix',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Strong labor data reduces recession concerns, compressing volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-10y',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Hot labor data lifts 10Y via growth/inflation expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { sign: 'mixed', strength: 2, confidence: 2 },
            inflation_scare: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-mortgage',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Higher yields from strong labor data pass through to mortgage rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-housing',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher mortgage rates from labor heat may dampen housing demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-gdp',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'gdp-growth',
        sign: 'up', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Strong employment supports consumption and eventually GDP growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-oil',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'up', strength: 2, lag: 'short', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Strong labor data signals robust demand, supporting oil prices.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-core-pce',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'core-pce',
        sign: 'up', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong wages feed into services prices, lifting core PCE over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-job-openings',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'job-openings',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Hot labor market confirms strong demand for workers and elevated openings.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: unemployment_higher_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'high-ue-to-unemployment',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Unemployment rate rises directly from the data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-2y',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Rising unemployment brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            inflation_scare: { sign: 'up', strength: 2, confidence: 2 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-10y',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'flight_to_quality',
        explanationTemplate: 'Weakening labor market triggers flight-to-quality into Treasuries.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-spending',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Rising unemployment reduces income and consumer confidence.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-gdp',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cooling labor market drags on consumption and GDP growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-wages',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Slack in the labor market reduces wage pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-sp500',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Rising unemployment raises recession fears, pressuring equities.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-nasdaq',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Labor weakness weighs on growth stock sentiment.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-dow',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Rising unemployment signals economic weakness, pressuring Dow.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-vix',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Rising unemployment increases economic uncertainty, lifting volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'high-ue-to-mortgage',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'mortgage-rates',
        sign: 'down', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Falling yields from labor weakness pass through to lower mortgage rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-housing',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'The demand hit from rising unemployment outweighs lower mortgage rate benefits.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-corporate',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 2, lag: 'short', confidence: 3,
        mechanism: 'credit_risk_repricing',
        explanationTemplate: 'Rising unemployment raises credit risk, widening corporate spreads.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-oil',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 2, lag: 'short', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Labor weakness signals softening demand, pressuring oil prices.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-core-cpi',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Rising unemployment builds slack, gradually easing core inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-job-openings',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Weakening labor demand is confirmed by falling job openings.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: consumer_spending_weaker
    // ═══════════════════════════════════════════════════════════
    {
        id: 'weak-spend-to-spending',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Consumer spending or retail sales print below expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-gdp',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 4, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Consumer spending is ~70% of GDP — weakness drags growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5, confidence: 5 },
            recession_risk: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Weak demand data brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-sp500',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer data weighs on earnings expectations and equities.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 4 },
        },
        surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-core-cpi',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weaker demand reduces pricing power, easing inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            inflation_scare: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-nasdaq',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer data weighs on growth stock earnings expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-dow',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer data drags Dow via reduced revenue expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-vix',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Weak spending data increases growth uncertainty and lifts volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-10y',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'flight_to_quality',
        explanationTemplate: 'Weak demand triggers modest flight-to-quality into Treasuries.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-mortgage',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'mortgage-rates',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Falling yields from weak demand data ease mortgage rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-housing',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weaker consumer activity signals reduced housing demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-corporate',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 2, lag: 'short', confidence: 2,
        mechanism: 'credit_risk_repricing',
        explanationTemplate: 'Weak consumer demand raises credit risk, widening corporate spreads.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-unemployment',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer spending leads firms to cut costs and slow hiring.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            late_cycle: { strength: 3 },
            recession_risk: { strength: 3 },
            financial_stress: { strength: 3 },
        },
        surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-wages',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak demand slows hiring and reduces wage bargaining power.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-oil',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 1, lag: 'short', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer activity signals lower energy demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-core-pce',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'core-pce',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak spending reduces demand-pull inflation pressure on core PCE.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-job-openings',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weaker consumer demand leads firms to reduce hiring plans.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: credit_spreads_widen_sharply
    // ═══════════════════════════════════════════════════════════
    {
        id: 'credit-to-corporate',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'credit_risk_repricing',
        explanationTemplate: 'Credit spreads blow out, sharply raising corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 4 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-sp500',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Credit stress signals risk-off, pressuring equities broadly.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5 },
            recession_risk: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-vix',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Financial stress lifts volatility as uncertainty spikes.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5 },
            recession_risk: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-10y',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'flight_to_quality',
        explanationTemplate: 'Credit stress triggers flight-to-quality into Treasuries, pushing yields down.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'credit-to-gdp',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter credit conditions reduce investment and slow economic growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'credit-to-dow',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Broad risk-off sentiment drags equities including the Dow.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 2 },
            late_cycle: { strength: 4 },
            recession_risk: { strength: 4 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'credit-to-nasdaq',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Risk-off hits growth stocks especially hard during credit stress.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            soft_landing: { strength: 3 },
            late_cycle: { strength: 5 },
            recession_risk: { strength: 5 },
            financial_stress: { strength: 5 },
        },
        surpriseScaling: null,
    },
    {
        id: 'credit-to-2y',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Credit stress signals growth slowdown, pulling rate-cut expectations forward.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-mortgage',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'credit_risk_repricing',
        explanationTemplate: 'Wider credit spreads pass through to higher mortgage rates despite falling Treasuries.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-housing',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher mortgage rates and tighter lending standards reduce housing activity.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-spending',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter credit conditions reduce consumer access to credit and spending.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-unemployment',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter credit slows growth and hiring, eventually lifting unemployment.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-wages',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Financial stress slows hiring and reduces wage bargaining power.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-oil',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'oil-barrel-price',
        sign: 'down', strength: 2, lag: 'short', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Credit stress signals growth weakness, reducing oil demand.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-core-cpi',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'long', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter credit slows demand and gradually eases core inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-job-openings',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'job-openings',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Financial stress leads firms to freeze or reduce hiring plans.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
];

// Helper: get all impact rules for a given scenario
function getRulesForScenario(scenarioId) {
    return IMPACT_RULES.filter((r) => r.scenarioId === scenarioId);
}
