// ===== LAYER 3: IMPACT RULES =====
// Scenario-to-indicator adjacency list. Each rule defines how a scenario affects a target indicator.
// Static, versioned, authoritative — the deterministic source of truth.
//
// sign:       'up' | 'down' | 'mixed'
// strength:   1–5 integer scale
// lag:        'immediate' | 'short' | 'medium' | 'long'
// confidence: 1–5 integer scale
// mechanism:  references MECHANISMS[].id (from mechanisms.js)

const IMPACT_RULES = [

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_hike_hawkish_surprise
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hike-to-fed-funds',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'fed-funds-target',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed directly sets the fed funds rate — a hike raises it mechanically.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.4 },
    },
    {
        id: 'hike-to-2y',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'A hawkish surprise reprices the expected fed funds path upward, lifting 2Y yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hike-to-10y',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Hawkish surprise pushes 10Y up via term premium, but recession fears can offset.',
        conditionalOn: null, exceptions: ['At zero lower bound, effect is muted'],
        regimeOverrides: {
            recession_risk: { sign: 'down', strength: 2, confidence: 3 },
        },
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hike-to-mortgage',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Higher yields pass through to mortgage rates with a short lag.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-sp500',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Higher rates raise discount rates, pressuring equity valuations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-nasdaq',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth/tech stocks are especially rate-sensitive due to long-duration cash flows.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-dow',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Dow falls but less than Nasdaq — its value-heavy composition is less rate-sensitive.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-vix',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Hawkish surprises increase uncertainty, lifting volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.5, medium: 1.0, large: 1.5 },
    },
    {
        id: 'hike-to-corporate',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Higher benchmark yields widen credit spreads and raise corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-housing',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 3, lag: 'medium', confidence: 4,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Higher mortgage rates make housing less affordable, reducing new construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-spending',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 2, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter financial conditions reduce disposable income and credit access.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },
    {
        id: 'hike-to-gdp',
        scenarioId: 'fed_hike_hawkish_surprise',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 2, lag: 'long', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter conditions slow investment and consumption, dragging on GDP over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_higher_for_longer
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hfl-to-forward-guidance',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'forward-guidance',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed explicitly signals rates will remain elevated for longer.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hfl-to-2y',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Markets push out the expected timeline for rate cuts, lifting short-end yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hfl-to-10y',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Higher-for-longer signals lift term premium, pushing 10Y yields up.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { sign: 'mixed', strength: 2, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'hfl-to-sp500',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Extended high rates pressure equity valuations through higher discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hfl-to-nasdaq',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks suffer most from sustained high rates due to duration sensitivity.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hfl-to-mortgage',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'mortgage-rates',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Sustained high yields keep mortgage rates elevated.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hfl-to-housing',
        scenarioId: 'fed_higher_for_longer',
        targetIndicatorId: 'housing-starts',
        sign: 'down', strength: 3, lag: 'medium', confidence: 4,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Persistently high mortgage rates dampen housing demand and construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: fed_cut_dovish_surprise
    // ═══════════════════════════════════════════════════════════
    {
        id: 'cut-to-fed-funds',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'fed-funds-target',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'The Fed directly lowers the fed funds rate.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.4 },
    },
    {
        id: 'cut-to-2y',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'A dovish surprise reprices the fed funds path lower, pulling 2Y yields down.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'cut-to-10y',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Dovish surprise lowers 10Y yields, though growth optimism can partially offset.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-sp500',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'sp-500',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Lower rates reduce discount rates, boosting equity valuations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            recession_risk: { sign: 'mixed', strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },
    {
        id: 'cut-to-nasdaq',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'nasdaq',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks benefit most from lower rates due to duration sensitivity.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-mortgage',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'mortgage-rates',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'pass_through_to_borrowing_rates',
        explanationTemplate: 'Lower yields pass through to mortgage rates, improving affordability.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-housing',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'housing-starts',
        sign: 'up', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Lower mortgage rates stimulate housing demand and new construction.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cut-to-vix',
        scenarioId: 'fed_cut_dovish_surprise',
        targetIndicatorId: 'vix',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Dovish surprises reduce uncertainty, compressing volatility.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: {
            financial_stress: { sign: 'mixed', strength: 1, confidence: 2 },
        },
        surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: core_pce_hotter_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hot-pce-to-core-pce',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'core-pce',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'Core PCE prints higher than expected — this is the direct data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-2y',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Hotter inflation pushes markets to price in fewer rate cuts or more hikes.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'hot-pce-to-10y',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'long_end_growth_inflation_mix',
        explanationTemplate: 'Hot inflation lifts 10Y via inflation expectations, but growth fears can offset.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-sp500',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Hot inflation means tighter policy ahead, pressuring equities.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-nasdaq',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks are hit hardest by hawkish repricing after hot inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-pce-to-core-cpi',
        scenarioId: 'core_pce_hotter_than_expected',
        targetIndicatorId: 'core-cpi',
        sign: 'up', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Persistent inflation pressure tends to show up in both PCE and CPI measures.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: core_pce_cooler_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'cool-pce-to-core-pce',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'core-pce',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'direct_policy_action',
        explanationTemplate: 'Core PCE prints lower than expected — this is the direct data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-2y',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Cooler inflation data brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.3 },
    },
    {
        id: 'cool-pce-to-sp500',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'sp-500',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Disinflation supports equities via lower expected discount rates.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'cool-pce-to-nasdaq',
        scenarioId: 'core_pce_cooler_than_expected',
        targetIndicatorId: 'nasdaq',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'discount_rate_duration_assets',
        explanationTemplate: 'Growth stocks rally on dovish repricing after cool inflation.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: payrolls_wages_hot
    // ═══════════════════════════════════════════════════════════
    {
        id: 'hot-labor-to-wages',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'wage-growth',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong payrolls and wage data directly show labor market heat.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-unemployment',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'unemployment',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong hiring typically pushes unemployment lower.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-2y',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'up', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Hot labor data signals the Fed may need to keep rates higher, lifting 2Y yields.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-core-cpi',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'core-cpi',
        sign: 'up', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Strong wage growth can feed into services inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'hot-labor-to-spending',
        scenarioId: 'payrolls_wages_hot',
        targetIndicatorId: 'consumer-spending',
        sign: 'up', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'More jobs and higher wages boost consumer spending power.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: unemployment_higher_than_expected
    // ═══════════════════════════════════════════════════════════
    {
        id: 'high-ue-to-unemployment',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'unemployment',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Unemployment rate rises directly from the data release.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-2y',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Rising unemployment brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-10y',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'flight_to_quality',
        explanationTemplate: 'Weakening labor market triggers flight-to-quality into Treasuries.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-spending',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 3, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Rising unemployment reduces income and consumer confidence.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-gdp',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Cooling labor market drags on consumption and GDP growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'high-ue-to-wages',
        scenarioId: 'unemployment_higher_than_expected',
        targetIndicatorId: 'wage-growth',
        sign: 'down', strength: 3, lag: 'short', confidence: 3,
        mechanism: 'labor_market_signal',
        explanationTemplate: 'Slack in the labor market reduces wage pressure.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: consumer_spending_weaker
    // ═══════════════════════════════════════════════════════════
    {
        id: 'weak-spend-to-spending',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'consumer-spending',
        sign: 'down', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Consumer spending or retail sales print below expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-gdp',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 4, lag: 'short', confidence: 4,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Consumer spending is ~70% of GDP — weakness drags growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-2y',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'front-end-yields-2y',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'policy_path_repricing',
        explanationTemplate: 'Weak demand data brings forward rate-cut expectations.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-sp500',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 2, lag: 'immediate', confidence: 3,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weak consumer data weighs on earnings expectations and equities.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'weak-spend-to-core-cpi',
        scenarioId: 'consumer_spending_weaker',
        targetIndicatorId: 'core-cpi',
        sign: 'down', strength: 2, lag: 'medium', confidence: 2,
        mechanism: 'demand_growth_signal',
        explanationTemplate: 'Weaker demand reduces pricing power, easing inflation over time.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },

    // ═══════════════════════════════════════════════════════════
    // SCENARIO: credit_spreads_widen_sharply
    // ═══════════════════════════════════════════════════════════
    {
        id: 'credit-to-corporate',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'corporate-borrowing',
        sign: 'up', strength: 5, lag: 'immediate', confidence: 5,
        mechanism: 'credit_risk_repricing',
        explanationTemplate: 'Credit spreads blow out, sharply raising corporate borrowing costs.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-sp500',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'sp-500',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Credit stress signals risk-off, pressuring equities broadly.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.7, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-vix',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'vix',
        sign: 'up', strength: 4, lag: 'immediate', confidence: 5,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Financial stress lifts volatility as uncertainty spikes.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null,
        surpriseScaling: { small: 0.6, medium: 1.0, large: 1.5 },
    },
    {
        id: 'credit-to-10y',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'long-end-yields-10y',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 3,
        mechanism: 'flight_to_quality',
        explanationTemplate: 'Credit stress triggers flight-to-quality into Treasuries, pushing yields down.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-gdp',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'gdp-growth',
        sign: 'down', strength: 3, lag: 'medium', confidence: 3,
        mechanism: 'financial_conditions_transmission',
        explanationTemplate: 'Tighter credit conditions reduce investment and slow economic growth.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-dow',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'dow',
        sign: 'down', strength: 3, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Broad risk-off sentiment drags equities including the Dow.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
    {
        id: 'credit-to-nasdaq',
        scenarioId: 'credit_spreads_widen_sharply',
        targetIndicatorId: 'nasdaq',
        sign: 'down', strength: 4, lag: 'immediate', confidence: 4,
        mechanism: 'risk_sentiment_volatility',
        explanationTemplate: 'Risk-off hits growth stocks especially hard during credit stress.',
        conditionalOn: null, exceptions: null,
        regimeOverrides: null, surpriseScaling: null,
    },
];

// Helper: get all impact rules for a given scenario
function getRulesForScenario(scenarioId) {
    return IMPACT_RULES.filter((r) => r.scenarioId === scenarioId);
}
